name: Update GitHub Stats

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update README
        run: |
          # Add a comment to force cache refresh without visible changes
          sed -i '1s/^/<!-- Last updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC") -->\n/' README.md
          
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README stats cache"
          git push 